package com.url.shortener.repository;

import java.util.Optional;

import org.springframework.data.jpa.repository.JpaRepository;

import com.url.shortener.models.User;

public interface UserRepository extends JpaRepository<User, Long>{
	
	/*
	 * Optional is a container object used to represent the presence or absence of a value.
	 * It is a way to prevent NullPointerExceptions.
	 * Optional can either contain a value or be empty.
	 * 
	 * And here we are adding a method for which the query will be generated by the jpa itself.
	 */
	Optional<User> findUserByUsername(String Username);
	
}
